language: ruby
rvm:
- 2.2.3
cache: bundler
env:
  global:
  - AWS_BUCKET=andreas.boehrnsen
  - AWS_REGION=us-east-1
  - secure: iZdb/JlIjotwUx2TpVR+n89T7INR3zyhXdSNbJ4ZNcOef3MxbD/KuQ5wJFKK9yF0XC9rHL1O+6rWqOtxTSUja0ubVoPZbcZgzzPiQz3Vxw4FQzEZWmKBXl6vKgZQ8tx86Zt0kC4kVGvbs5iOcqD4XapMteMVthsq5aYCtEJNpak=
  - secure: Ca/U4fMVDWIaWRsAiokrIJc45jY6hxoR5cKRa9dWg4ma+u5m4tzbVsOpFNj1q9ZO99lRP6E5n4WXNAO5eI+CsKDFvYeAs89DInwT0nIS+Y66adV4uOCBAib8axS1fgU8ggf1UelIqsMAhkcMF4n5n0SadcKWcBZ56L5RLfJ18M8=
  - secure: K8akTYO2+S1c/f6pdlMtH2Zv3TlU8DgQ7lnxmIXor/Zv4QsTKdIgbjyUI7jgiRqKzFkEP/3y2l0byFLwMAGIDBLzTA2yfHXAE7y5/hZWF8XteBea4nB7fqWM8o4xS2lj5mdS4cYHp5HfRQ9bLNt+yFzHlU6TVXRy3pwdVqil9vA=
sudo: false
script:
- bundle exec middleman build
after_success:
- bundle exec middleman sync
- bundle exec middleman invalidate
